# Description
# ===========
# This playbook updates existing nics
---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ resource_group_name }}"

  - name: Update virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ virtual_network }}"
      subnet_name: "{{ subnet_name }}"
      security_group: "{{ security_group }}"
      ip_configurations:
      - name: "{{ ip_config_name }}"
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant_id }}"
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
      state: present
