# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH
---
- hosts: all
  pre_tasks:
    - name: Verify Ansible meets Drupal VM's version requirements.
      assert:
        that: "ansible_version.full is version_compare('2.5.0', '>=')"
        msg: >
          "You must update Ansible to at least 2.5.1"
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ resource_group_name }}"
  tasks:
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ nic_resource_group_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ virtual_network }}"
      subnet_name: "{{ subnet_name }}"
      create_with_security_group: True
      security_group: Nsg_private
      ip_configurations:
      - name: "{{ ip_configuration_name }}"
        primary: True
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant }}"
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      subscription_id: "{{ subscription_id }}"  
      tenant: "{{ tenant }}"
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
      vm_size: "{{ vm_size }}"
      managed_disk_type: "{{ managed_disk_type }}"
      location: "{{ location }}"
      admin_username: azureuser
      admin_password: Password@123
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      network_interfaces: "/subscriptions/d1bb81b6-4764-4663-9552-c15071377ff5/resourceGroups/RG_WESTUS2/providers/Microsoft.Network/networkInterfaces/anish_nic2"
      image:
        offer: "{{ os_name }}"
        publisher: "{{ publisher }}"
        sku: "{{ sku }}"
        version: "{{ version }}"
      data_disks:
        - lun: 0
          disk_size_gb: 1
          managed_disk_type: Standard_LRS
