# Description
# ===========
# This playbook creates multiple disks/nics
---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "{{ resource_group_name }}"
    data_disk_sizes: "{{ disk_sizes.split(',') }}"
    data_disk_types: "{{ disk_types.split(',') }}"
    data_disk_luns: "{{ disk_luns.split(',') }}"

  tasks:
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ nic_resource_group_name }}"
      name: "{{ nic_name }}"
      virtual_network: "{{ virtual_network }}"
      subnet_name: "{{ subnet_name }}"
      security_group: Nsg_private
      ip_configurations:
      - name: "{{ ip_configuration_name }}"
        primary: True
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant }}"
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      subscription_id: "{{ subscription_id }}"  
      tenant: "{{ tenant }}"
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
      vm_size: "{{ vm_size }}"
      managed_disk_type: "{{ managed_disk_type }}"
      admin_username: azureuser
      admin_password: Password@123
      virtual_network_resource_group : "{{ nic_resource_group_name }}"
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ ssh_key }}"
      network_interfaces: "{{ nic_name }}"
      image:
        offer: "{{ os_name }}"
        publisher: "{{ publisher }}"
        sku: "{{ sku }}"
        version: "{{ version }}"
      data_disks:
        - lun: "{{ item.2 }}"
          disk_size_gb: "{{ item.0 }}"
          managed_disk_type: "{{ item.1 }}"
    loop: "{{ data_disk_sizes|zip(data_disk_types, data_disk_luns)|list }}"
